name: DeFi Wallet Risk Scorer Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests with pytest
      run: |
        python tests.py
    
    - name: Test scoring system with simulation
      run: |
        python score_wallets_improved.py --simulation --quiet
        ls -la *.csv *.png *.log
    
    - name: Validate output files
      run: |
        # Check that required output files were created
        test -f wallet_scores.csv
        test -f wallet_features.csv
        test -f score_distribution.png
        test -f scoring.log
        
        # Check that CSV files have the expected format
        head -5 wallet_scores.csv
        wc -l wallet_scores.csv
